package builder

import (
	"fmt"
	"net/url"
	"strings"
	"text/template"

	"frostroot/internal/distro"
	"frostroot/internal/recipe"
)

// FedoraBasePackages are in every Fedora image besides the recipe's own: a
// lean base for WSL, which the owner chose over Fedora's @core (decision 6
// in docs/superpowers/specs/2026-09-28-frostroot-fedora.md). dnf5 is here
// because an image without it has no rpm database at all: mkosi removes the
// database of a package manager the image lacks.
var FedoraBasePackages = []string{
	"systemd", "sudo", "passwd", "tzdata", "ca-certificates", "dnf5",
	"bash", "coreutils", "util-linux", "procps-ng", "iproute", "iputils",
	"less", "vim-minimal", "which", "findutils", "hostname", "shadow-utils",
	"grep", "sed", "gawk", "tar", "gzip", "xz", "curl", "man-db",
}

// fedoraToolsPackages are the tools tree's: what mkosi runs from it to make
// the image. rpm comes with dnf5, and is named because its version is part of
// the image's bytes.
var fedoraToolsPackages = []string{
	"bash", "coreutils", "util-linux", "dnf5", "rpm", "bubblewrap",
	"tar", "gzip", "zstd", "systemd", "ca-certificates",
}

// Where frostroot's files are, relative to a package manager tree. mkosi
// binds each of the tree's etc directories over the sandbox's own, so dnf
// sees them at /etc/frostroot-keys and /etc/frostroot-trust.
const (
	fedoraKeysDir  = "etc/frostroot-keys"
	fedoraTrustDir = "etc/frostroot-trust"
)

// Names of what mkosi writes into its output directory: the tools tree, a
// directory; and the image, an uncompressed tar, with the finalize script's
// records beside it. They start with the output's name, because mkosi
// renames anything else a script leaves there.
const (
	mkosiToolsOutput         = "tools"
	mkosiImageOutput         = "image"
	fedoraToolsInstalledFile = "tools.installed"  // the tools tree's packages, as rpm lists them
	fedoraInstalledFile      = "image.installed"  // the image's packages, with dnf5's reasons and origins
	fedoraLocationsFile      = "image.locations"  // where dnf5 found each of the image's packages
	fedoraReasonsFile        = "packages.toml"    // offline: dnf5's reasons as the lock records them
	fedoraProvisionName      = "provision.chroot" // .chroot: mkosi runs it inside the image
	fedoraFinalizeName       = "finalize"
	// fedoraPackageManagerTree is the directory, in each of mkosi's two
	// configuration directories, that mkosi configures dnf from.
	fedoraPackageManagerTree = "package-manager-tree"
)

// fedoraKeyFileName is the name of release's key file in the package manager
// tree.
func fedoraKeyFileName(release distro.FedoraRelease) string {
	return "RPM-GPG-KEY-fedora-" + release.Version + "-primary"
}

// fedoraRepositories describes the repositories one of mkosi's two builds
// installs from.
type fedoraRepositories struct {
	release distro.FedoraRelease
	// local maps a repository's name to the directory it is served from
	// offline; empty online, when each is reached through its metalink.
	local map[string]string
	// caBundle is the path, inside the sandbox, of the certificates dnf
	// verifies HTTPS with instead of its own store; "" keeps its own.
	caBundle string
	insecure bool // --insecure: dnf verifies no certificate; packages are still checked against the key
}

// renderFedoraRepos renders the repository file of a package manager tree.
// Every package is checked against the release's key whatever the
// repository; repomd.xml is not signed, and online its checksum comes from
// the metalink over HTTPS.
func renderFedoraRepos(repositories fedoraRepositories) (string, error) {
	var text strings.Builder
	text.WriteString("# Generated by frostroot.\n")
	for _, repository := range repositories.release.Repositories {
		fmt.Fprintf(&text, "\n[%s]\nname=%s\n", repository.ID, repository.ID)
		if directory, offline := repositories.local[repository.ID]; offline {
			if strings.ContainsAny(directory, "\n\r") {
				return "", fmt.Errorf("%w: %q holds a line break, which a repository file cannot carry", ErrBadWorkRoot, directory)
			}
			fmt.Fprintf(&text, "baseurl=%s\n", (&url.URL{Scheme: "file", Path: directory}).String())
		} else {
			fmt.Fprintf(&text, "metalink=%s\n", repository.Metalink)
		}
		text.WriteString("enabled=1\ngpgcheck=1\nrepo_gpgcheck=0\n")
		fmt.Fprintf(&text, "gpgkey=file:///%s/%s\n", fedoraKeysDir, fedoraKeyFileName(repositories.release))
		if repositories.caBundle != "" {
			fmt.Fprintf(&text, "sslcacert=%s\n", repositories.caBundle)
		}
		if repositories.insecure {
			text.WriteString("sslverify=0\n")
		}
	}
	return text.String(), nil
}

// fedoraMkosiConf is what one of mkosi's two builds makes.
type fedoraMkosiConf struct {
	release   distro.FedoraRelease
	image     bool     // the image, as an uncompressed tar; otherwise the tools tree, a directory
	packages  []string // validated names, one per line
	recommend bool     // install weak dependencies
}

// renderFedoraMkosiConf renders mkosi.conf. Everything that names a path is
// given on mkosi's command line instead: a setting in this file cannot be
// overridden there.
func renderFedoraMkosiConf(conf fedoraMkosiConf) string {
	var text strings.Builder
	text.WriteString("# Generated by frostroot.\n")
	fmt.Fprintf(&text, "[Distribution]\nDistribution=fedora\nRelease=%s\nArchitecture=x86-64\n\n", conf.release.Version)
	if conf.image {
		// Uncompressed: mkosi's gzip writes the time into its header, and
		// the tarball is compressed afterwards with gzip -n.
		fmt.Fprintf(&text, "[Output]\nFormat=tar\nCompressOutput=no\nOutput=%s\n\n", mkosiImageOutput)
	} else {
		fmt.Fprintf(&text, "[Output]\nFormat=directory\nOutput=%s\n\n", mkosiToolsOutput)
	}
	text.WriteString("[Content]\nBootable=no\n")
	fmt.Fprintf(&text, "WithRecommends=%s\n", yesNo(conf.recommend))
	if conf.image {
		// Documentation stays, as dnf keeps it and as Ubuntu images have
		// it; and so does the package managers' own state, which mkosi
		// would otherwise judge by whether the image has them.
		text.WriteString("WithDocs=yes\nCleanPackageMetadata=no\n")
	}
	text.WriteString("Packages=")
	text.WriteString(strings.Join(conf.packages, "\n         "))
	text.WriteString("\n")
	return text.String()
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

// FedoraPackagesToInstall returns the recipe's packages, then the langpack
// its locale needs, then FedoraBasePackages, without duplicates.
func FedoraPackagesToInstall(imageRecipe recipe.Recipe) []string {
	var packages []string
	listed := map[string]bool{}
	add := func(name string) {
		if name != "" && !listed[name] {
			listed[name] = true
			packages = append(packages, name)
		}
	}
	for _, name := range imageRecipe.Packages.Include {
		add(name)
	}
	add(fedoraLangpack(imageRecipe))
	for _, name := range FedoraBasePackages {
		add(name)
	}
	return packages
}

// fedoraLangpack returns the glibc langpack that holds the recipe's locale,
// such as glibc-langpack-tr for tr_TR.UTF-8, or "" for C.UTF-8, which glibc
// has built in.
func fedoraLangpack(imageRecipe recipe.Recipe) string {
	locale := imageRecipe.Locale.Lang
	if locale == "" {
		locale = defaultLocale
	}
	languageAndTerritory, _, _ := strings.Cut(locale, ".")
	language, _, _ := strings.Cut(languageAndTerritory, "_")
	if language == "C" || language == "POSIX" {
		return ""
	}
	return "glibc-langpack-" + language
}

// fedoraProvisionTemplate runs as root inside the image after the packages
// are in, as mkosi's post-installation script. The files it installs were
// rendered into mkosi's source directory, which mkosi-chroot binds into the
// image as $SRCDIR. Recipe values are assigned once, single-quoted, and only
// expanded in double quotes afterwards.
var fedoraProvisionTemplate = template.Must(template.New("provision").Funcs(template.FuncMap{"shellQuote": shellQuote}).Parse(
	`# Generated by frostroot. Runs as root inside the image during the build.
set -eu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
export PATH

user={{shellQuote .UserName}}
lang={{shellQuote .Locale}}
want={{shellQuote .LocaleID}}
tz={{shellQuote .Timezone}}

# validate cannot see tzdata, so a zone the image does not have fails here.
if ! test -f "/usr/share/zoneinfo/$tz"; then
	echo "frostroot: timezone $tz does not exist in this image" >&2
	exit 1
fi
ln -sfn "../usr/share/zoneinfo/$tz" /etc/localtime

useradd --create-home --shell /bin/bash --user-group "$user"
{{- if .Sudo}}
usermod --append --groups wheel "$user"
install -m 0440 -o root -g root "$SRCDIR/sudoers" /etc/sudoers.d/90-frostroot
visudo -cqf /etc/sudoers.d/90-frostroot
{{- end}}
install -m 0644 -o root -g root "$SRCDIR/wsl.conf" /etc/wsl.conf

# The langpack was installed with the packages; a locale it does not hold
# fails here rather than at the first login.
if ! locale -a | tr 'A-Z' 'a-z' | tr -d '-' | grep -Fqx "$want"; then
	echo "frostroot: locale $lang is not in this image; is its glibc langpack a Fedora package?" >&2
	exit 1
fi
printf 'LANG=%s\n' "$lang" > /etc/locale.conf
`))

// RenderFedoraProvisionScript renders the script that sets the timezone,
// creates the user, gives sudo, installs wsl.conf and sets the locale inside
// a Fedora image.
func RenderFedoraProvisionScript(imageRecipe recipe.Recipe) (string, error) {
	locale := imageRecipe.Locale.Lang
	if locale == "" {
		locale = defaultLocale
	}
	timezone := imageRecipe.Locale.Timezone
	if timezone == "" {
		timezone = defaultTimezone
	}
	languageAndTerritory, codeset, _ := strings.Cut(locale, ".")
	var script strings.Builder
	err := fedoraProvisionTemplate.Execute(&script, provisionScriptValues{
		UserName: imageRecipe.User.Name,
		Locale:   locale,
		LocaleID: strings.ToLower(languageAndTerritory) + "." + strings.ToLower(strings.ReplaceAll(codeset, "-", "")),
		Timezone: timezone,
		Sudo:     imageRecipe.User.Sudo,
	})
	if err != nil {
		return "", fmt.Errorf("rendering provision script: %w", err)
	}
	return script.String(), nil
}

// fedoraImageFinalizeTemplate runs last, outside the image, in the tools
// tree: it records what dnf5 installed and from where, then removes what the
// build leaves that is not the image's. The records come first, because
// reading rpm's database recreates its SQLite side files. No pipe: every
// command's failure fails the build.
var fedoraImageFinalizeTemplate = template.Must(template.New("finalize").Funcs(template.FuncMap{"shellQuote": shellQuote}).Parse(
	`# Generated by frostroot. mkosi runs it last, outside the image.
set -eu
# HOME=/, as mkosi runs dnf: the sandbox's user has no home dnf5 can find,
# and rpm reads no one's macros.
dnf() {
	HOME=/ dnf5 --installroot="$BUILDROOT" --use-host-config --releasever={{shellQuote .Release}} \
		--setopt=cachedir=/var/cache/libdnf5 --setopt=persistdir=/var/lib/libdnf5 "$@"
}
{{- if .RestoreReasons}}

# Every package was asked for by name, so dnf5 recorded each as the user's.
# The lock says why each was installed when it was written.
cat "$SRCDIR/{{.ReasonsFile}}" > "$BUILDROOT/usr/lib/sysimage/libdnf5/packages.toml"
{{- end}}

dnf repoquery --installed --queryformat '%{full_nevra}|%{reason}|%{from_repo}|%{sourcerpm}\n' > "$OUTPUTDIR/{{.Installed}}"
{{- if .RecordLocations}}
nevras=$(cut -d '|' -f 1 "$OUTPUTDIR/{{.Installed}}")
set -f
# Unquoted on purpose: one argument per package, none holding a space.
dnf --cacheonly repoquery --available --queryformat '%{full_nevra}|%{repoid}|%{location}\n' $nevras > "$OUTPUTDIR/{{.Locations}}"
set +f
{{- end}}

# dnf5 logs into its install root whatever it is told: mkosi removes the log
# after each of its own runs, and the queries above wrote a new one, dated
# now and naming the build's paths.
rm -f "$BUILDROOT/usr/lib/sysimage/libdnf5/transaction_history.sqlite" \
	"$BUILDROOT/usr/lib/sysimage/libdnf5/transaction_history.sqlite-shm" \
	"$BUILDROOT/usr/lib/sysimage/libdnf5/transaction_history.sqlite-wal" \
	"$BUILDROOT/usr/lib/sysimage/libdnf5/system-repo.lock" \
	"$BUILDROOT/usr/lib/sysimage/rpm/rpmdb.sqlite-shm" \
	"$BUILDROOT/usr/lib/sysimage/rpm/rpmdb.sqlite-wal" \
	"$BUILDROOT/var/lib/libdnf5/system-repo.lock" \
	"$BUILDROOT/var/log/dnf5.log" \
	"$BUILDROOT/var/cache/ldconfig/aux-cache" \
	"$BUILDROOT/etc/resolv.conf"
`))

// renderFedoraImageFinalize renders the image build's finalize script. Online
// it also records where dnf5 found each package, which the lock needs;
// offline it puts dnf5's reasons back from the lock instead.
func renderFedoraImageFinalize(release distro.FedoraRelease, offline bool) (string, error) {
	var script strings.Builder
	err := fedoraImageFinalizeTemplate.Execute(&script, map[string]any{
		"Release":         release.Version,
		"RestoreReasons":  offline,
		"RecordLocations": !offline,
		"ReasonsFile":     fedoraReasonsFile,
		"Installed":       fedoraInstalledFile,
		"Locations":       fedoraLocationsFile,
	})
	if err != nil {
		return "", fmt.Errorf("rendering finalize script: %w", err)
	}
	return script.String(), nil
}

// fedoraToolsFinalize is the tools tree build's finalize script, run with
// the host's tools: it records the tools tree's packages. The host's
// Debian-patched rpm keeps the tree's database at its root, /.rpmdb.
const fedoraToolsFinalize = `# Generated by frostroot. mkosi runs it last, outside the tools tree.
set -eu
if test -d "$BUILDROOT/.rpmdb"; then
	dbpath=/.rpmdb
else
	dbpath=/usr/lib/sysimage/rpm
fi
rpm --root "$BUILDROOT" --dbpath "$dbpath" -qa \
	--queryformat '%{NAME}|%{EPOCHNUM}|%{VERSION}|%{RELEASE}|%{ARCH}|%{SOURCERPM}\n' > "$OUTPUTDIR/` + fedoraToolsInstalledFile + `"
`
