package builder

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"frostroot/internal/recipe"
)

// Essentials are added to every build. systemd and systemd-sysv are here
// because --variant=important does not include them, and without systemd the
// "[boot] systemd=true" in wsl.conf does nothing. ca-certificates is here so
// "git clone https://..." works in the image.
var Essentials = []string{
	"systemd", "systemd-sysv", "dbus",
	"sudo", "locales", "tzdata", "passwd", "ca-certificates",
}

const (
	defaultLang     = "en_US.UTF-8"
	defaultTimezone = "UTC"
	sudoersDropIn   = "/etc/sudoers.d/90-frostroot"
)

// MergeInclude returns the recipe's packages followed by the essentials,
// without duplicates.
func MergeInclude(user []string) []string {
	seen := map[string]bool{}
	var out []string
	add := func(p string) {
		if p == "" || seen[p] {
			return
		}
		seen[p] = true
		out = append(out, p)
	}
	for _, p := range user {
		add(p)
	}
	for _, p := range Essentials {
		add(p)
	}
	return out
}

// RenderWSLConf renders /etc/wsl.conf.
func RenderWSLConf(r recipe.Recipe) string {
	var b strings.Builder
	if r.WSL.Systemd {
		b.WriteString("[boot]\nsystemd=true\n\n")
	}
	fmt.Fprintf(&b, "[user]\ndefault=%s\n", recipe.DefaultUser(r))
	// WSL otherwise rewrites /etc/localtime to the Windows zone every time the
	// distro starts, and the recipe's timezone would never take effect.
	b.WriteString("\n[time]\nuseWindowsTimezone=false\n")
	return b.String()
}

// RenderSudoers renders the sudoers drop-in, or "" when the user gets no sudo.
func RenderSudoers(r recipe.Recipe) string {
	if !r.User.Sudo {
		return ""
	}
	return fmt.Sprintf("%s ALL=(ALL) NOPASSWD:ALL\n", r.User.Name)
}

// provisionTmpl runs as root inside the image, near the end of the build.
// Recipe values are assigned once, single-quoted, and only ever expanded in
// double quotes afterwards, so they are never parsed as shell. It checks
// results rather than exit codes where a tool is known to succeed at nothing.
var provisionTmpl = template.Must(template.New("provision").Funcs(template.FuncMap{"sq": sq}).Parse(
	`# Generated by frostroot. Runs as root inside the image during the build.
set -eu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH

user={{sq .User}}
lang={{sq .Lang}}
charmap={{sq .Charmap}}
want={{sq .LocaleID}}
tz={{sq .Timezone}}

# validate cannot see tzdata, so a zone the image does not have fails here.
if ! test -f "/usr/share/zoneinfo/$tz"; then
	echo "frostroot: timezone $tz does not exist in this image" >&2
	exit 1
fi
ln -sfn "/usr/share/zoneinfo/$tz" /etc/localtime
printf '%s\n' "$tz" > /etc/timezone

useradd --create-home --shell /bin/bash --user-group "$user"
{{- if .Sudo}}

# The drop-in was uploaded by an earlier hook.
chmod 0440 /etc/sudoers.d/90-frostroot
visudo -cqf /etc/sudoers.d/90-frostroot
{{- end}}

# locale-gen exits 0 without generating anything when /etc/locale.gen is empty,
# so check the result instead of trusting the exit code.
have_locale() {
	locale -a | tr 'A-Z' 'a-z' | tr -d '-' | grep -Fqx "$want"
}
if ! have_locale; then
	printf '%s %s\n' "$lang" "$charmap" >> /etc/locale.gen
	locale-gen
	if ! have_locale; then
		echo "frostroot: locale $lang was not generated; is it listed in /usr/share/i18n/SUPPORTED?" >&2
		exit 1
	fi
fi
update-locale "LANG=$lang"

# mmdebstrap copies these from the build host and leaves them behind.
rm -f /etc/resolv.conf /etc/hostname
`))

// RenderProvision renders the script that sets the timezone, creates the
// user, enables sudo and generates the locale inside the image.
func RenderProvision(r recipe.Recipe) string {
	lang := r.Locale.Lang
	if lang == "" {
		lang = defaultLang
	}
	tz := r.Locale.Timezone
	if tz == "" {
		tz = defaultTimezone
	}
	name, codeset, _ := strings.Cut(lang, ".")
	folded := strings.ToLower(strings.ReplaceAll(codeset, "-", ""))
	charmap := codeset
	if folded == "utf8" {
		charmap = "UTF-8"
	}
	var b strings.Builder
	err := provisionTmpl.Execute(&b, struct {
		User, Lang, Charmap, LocaleID, Timezone string
		Sudo                                    bool
	}{
		User:     r.User.Name,
		Lang:     lang,
		Charmap:  charmap,
		LocaleID: strings.ToLower(name) + "." + folded, // as `locale -a` lists it, folded
		Timezone: tz,
		Sudo:     r.User.Sudo,
	})
	if err != nil {
		panic(err) // the template is static and its data is plain strings
	}
	return b.String()
}

// Stage holds the host-side paths the hooks reference.
type Stage struct {
	WSLConf   string // rendered /etc/wsl.conf, uploaded into the image
	Sudoers   string // rendered sudoers drop-in; empty when user.sudo is false
	Provision string // rendered provision script, run inside the image
	StatusOut string // where the image's dpkg status file is downloaded to
}

// WriteStage renders every provisioning file into dir. This is the only code
// path that produces them; the hooks only place and run them.
func WriteStage(dir string, r recipe.Recipe) (Stage, error) {
	st := Stage{
		WSLConf:   filepath.Join(dir, "wsl.conf"),
		Provision: filepath.Join(dir, "provision.sh"),
		StatusOut: filepath.Join(dir, "dpkg-status"),
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return Stage{}, err
	}
	files := map[string]string{
		st.WSLConf:   RenderWSLConf(r),
		st.Provision: RenderProvision(r),
	}
	if body := RenderSudoers(r); body != "" {
		st.Sudoers = filepath.Join(dir, "sudoers")
		files[st.Sudoers] = body
	}
	for path, body := range files {
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return Stage{}, err
		}
	}
	return st, nil
}

// sq single-quotes a value for the shell. validate already constrains every
// recipe value; this is the second line of defence, and it also covers host
// paths such as the work directory, which frostroot does not choose.
func sq(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

// CustomizeHooks returns mmdebstrap --customize-hook arguments, in order.
// Every hook fails the build on error. upload and download arguments are
// split by mmdebstrap with shellwords, so quoting host paths is correct there
// too. The provision script is read from the stage directory rather than
// copied into the image, so nothing is left behind.
func CustomizeHooks(st Stage) []string {
	hooks := []string{"upload " + sq(st.WSLConf) + " /etc/wsl.conf"}
	if st.Sudoers != "" {
		hooks = append(hooks, "upload "+sq(st.Sudoers)+" "+sudoersDropIn)
	}
	return append(hooks,
		`chroot "$1" /bin/sh -c "$(cat `+sq(st.Provision)+`)" frostroot-provision`,
		// Last, so the status reflects everything installed.
		"download /var/lib/dpkg/status "+sq(st.StatusOut),
	)
}
