package builder

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"

	"frostroot/internal/recipe"
)

// EssentialPackages are installed in every image. systemd and systemd-sysv are
// here because --variant=important does not include them, and without systemd
// the "[boot] systemd=true" in wsl.conf does nothing. ca-certificates is here
// so that "git clone https://..." works in the image.
var EssentialPackages = []string{
	"systemd", "systemd-sysv", "dbus",
	"sudo", "locales", "tzdata", "passwd", "ca-certificates",
}

const (
	defaultLocale       = "en_US.UTF-8"
	defaultTimezone     = "UTC"
	sudoersDropInPath   = "/etc/sudoers.d/90-frostroot"
	provisionScriptName = "frostroot-provision" // $0 of the script, shown in its error messages
)

// PackagesToInstall returns the recipe's requested packages followed by the
// essential packages, without duplicates.
func PackagesToInstall(requestedPackages []string) []string {
	var packages []string
	alreadyListed := map[string]bool{}
	addOnce := func(packageName string) {
		if packageName == "" || alreadyListed[packageName] {
			return
		}
		alreadyListed[packageName] = true
		packages = append(packages, packageName)
	}
	for _, packageName := range requestedPackages {
		addOnce(packageName)
	}
	for _, packageName := range EssentialPackages {
		addOnce(packageName)
	}
	return packages
}

// RenderWSLConf renders /etc/wsl.conf for imageRecipe.
func RenderWSLConf(imageRecipe recipe.Recipe) string {
	var wslConf strings.Builder
	if imageRecipe.WSL.Systemd {
		wslConf.WriteString("[boot]\nsystemd=true\n\n")
	}
	fmt.Fprintf(&wslConf, "[user]\ndefault=%s\n", recipe.DefaultUser(imageRecipe))
	// WSL otherwise rewrites /etc/localtime to the Windows zone every time the
	// distribution starts, and the recipe's timezone would never take effect.
	wslConf.WriteString("\n[time]\nuseWindowsTimezone=false\n")
	return wslConf.String()
}

// RenderSudoers renders the sudoers drop-in for imageRecipe, or returns ""
// when the user gets no sudo.
func RenderSudoers(imageRecipe recipe.Recipe) string {
	if !imageRecipe.User.Sudo {
		return ""
	}
	return fmt.Sprintf("%s ALL=(ALL) NOPASSWD:ALL\n", imageRecipe.User.Name)
}

// provisionScriptTemplate runs as root inside the image, near the end of the
// build. Recipe values are assigned once, single-quoted, and only ever
// expanded in double quotes afterwards, so they are never parsed as shell. The
// script checks results rather than exit codes where a tool is known to
// succeed at nothing.
var provisionScriptTemplate = template.Must(template.New("provision").Funcs(template.FuncMap{"shellQuote": shellQuote}).Parse(
	`# Generated by frostroot. Runs as root inside the image during the build.
set -eu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH

user={{shellQuote .UserName}}
lang={{shellQuote .Locale}}
charmap={{shellQuote .Charmap}}
want={{shellQuote .LocaleID}}
tz={{shellQuote .Timezone}}

# validate cannot see tzdata, so a zone the image does not have fails here.
if ! test -f "/usr/share/zoneinfo/$tz"; then
	echo "frostroot: timezone $tz does not exist in this image" >&2
	exit 1
fi
ln -sfn "/usr/share/zoneinfo/$tz" /etc/localtime
printf '%s\n' "$tz" > /etc/timezone

useradd --create-home --shell /bin/bash --user-group "$user"
{{- if .Sudo}}

# The drop-in was uploaded by an earlier hook.
chmod 0440 /etc/sudoers.d/90-frostroot
visudo -cqf /etc/sudoers.d/90-frostroot
{{- end}}

# locale-gen exits 0 without generating anything when /etc/locale.gen is empty,
# so check the result instead of trusting the exit code.
have_locale() {
	locale -a | tr 'A-Z' 'a-z' | tr -d '-' | grep -Fqx "$want"
}
if ! have_locale; then
	printf '%s %s\n' "$lang" "$charmap" >> /etc/locale.gen
	locale-gen
	if ! have_locale; then
		echo "frostroot: locale $lang was not generated; is it listed in /usr/share/i18n/SUPPORTED?" >&2
		exit 1
	fi
fi
update-locale "LANG=$lang"

# mmdebstrap copies these from the build host and leaves them behind.
rm -f /etc/resolv.conf /etc/hostname
`))

// provisionScriptValues are the values the provision script template needs.
type provisionScriptValues struct {
	UserName string
	Locale   string // such as en_US.UTF-8
	Charmap  string // character map for /etc/locale.gen, such as UTF-8
	LocaleID string // the locale as `locale -a` lists it, lowercased without dashes
	Timezone string
	Sudo     bool
}

// RenderProvisionScript renders the script that sets the timezone, creates the
// user, enables sudo and generates the locale inside the image.
func RenderProvisionScript(imageRecipe recipe.Recipe) (string, error) {
	locale := imageRecipe.Locale.Lang
	if locale == "" {
		locale = defaultLocale
	}
	timezone := imageRecipe.Locale.Timezone
	if timezone == "" {
		timezone = defaultTimezone
	}
	languageAndTerritory, codeset, _ := strings.Cut(locale, ".")
	normalizedCodeset := strings.ToLower(strings.ReplaceAll(codeset, "-", ""))
	charmap := codeset
	if normalizedCodeset == "utf8" {
		charmap = "UTF-8"
	}
	var script strings.Builder
	err := provisionScriptTemplate.Execute(&script, provisionScriptValues{
		UserName: imageRecipe.User.Name,
		Locale:   locale,
		Charmap:  charmap,
		LocaleID: strings.ToLower(languageAndTerritory) + "." + normalizedCodeset,
		Timezone: timezone,
		Sudo:     imageRecipe.User.Sudo,
	})
	if err != nil {
		return "", fmt.Errorf("rendering provision script: %w", err)
	}
	return script.String(), nil
}

// Stage holds the paths, on the build host, of the files the customize hooks
// place into or copy out of the image.
type Stage struct {
	WSLConfPath         string // rendered /etc/wsl.conf, uploaded into the image
	SudoersPath         string // rendered sudoers drop-in; empty when the user gets no sudo
	SourcesListPath     string // rendered /etc/apt/sources.list; only an offline build uploads one
	ProvisionScriptPath string // rendered provision script, run inside the image
	DpkgStatusPath      string // where the image's dpkg status file is downloaded to
	// AptListsDir is where the image's /var/lib/apt/lists is copied to, for
	// the checksums the lock records; empty when the build does not need
	// them. mmdebstrap's copy-out puts the directory inside its destination,
	// so this is <stage>/lists and the hook names the stage directory.
	AptListsDir string
	// ExtendedStatesPath is where the image's /var/lib/apt/extended_states,
	// apt's record of the packages it installed on its own, is downloaded
	// to, for the auto marks the lock records; empty when the build does not
	// need them.
	ExtendedStatesPath string
	// AutoMarksPath is a rendered extended_states that restores the lock's
	// auto marks in an offline image, uploaded into it; empty when there is
	// nothing to restore.
	AutoMarksPath string
	// KeyringDir holds the binary signing keys of the recipe's extra
	// sources, one KeyringFileName each, for mmdebstrap's signed-by on the
	// host and for upload into the image. KeyNames lists them in order.
	KeyringDir string
	KeyNames   []string
}

// StageOptions say what WriteStage renders besides the provisioning files.
type StageOptions struct {
	// SourceLines are written as /etc/apt/sources.list for the image, with
	// signed-by paths under ImageKeyringDir. mmdebstrap would otherwise
	// leave the lines it was given, which name host paths (or, offline, the
	// local repository).
	SourceLines []string
	// RecordForLock asks for what an online build reads to write the lock:
	// the image's apt indexes, copied out for the checksums, and its
	// extended_states, downloaded for the auto marks.
	RecordForLock bool
	// AutoMarks is the extended_states an offline build uploads into the
	// image, rendered from the lock with RenderExtendedStates; "" uploads
	// nothing. apt marks no package on its own offline, because every locked
	// package is asked for by name.
	AutoMarks string
	// Keys are the extra sources' signing keys in binary form, by source
	// name, to stage for apt and upload into the image.
	Keys map[string][]byte
}

// WriteStage renders every provisioning file for imageRecipe into stageDir.
// This is the only code that produces them; the hooks only place and run
// them. Modes are set explicitly because the provision hook reads its script
// from inside mmdebstrap's user namespace, where it is "other" to these files.
func WriteStage(stageDir string, imageRecipe recipe.Recipe, options StageOptions) (Stage, error) {
	stage := Stage{
		WSLConfPath:         filepath.Join(stageDir, "wsl.conf"),
		ProvisionScriptPath: filepath.Join(stageDir, "provision.sh"),
		DpkgStatusPath:      filepath.Join(stageDir, "dpkg-status"),
	}
	if options.RecordForLock {
		stage.AptListsDir = filepath.Join(stageDir, "lists")
		stage.ExtendedStatesPath = filepath.Join(stageDir, "extended-states")
	}
	if err := makeDirectoriesWithMode(stageDir, 0o755); err != nil {
		return Stage{}, err
	}
	provisionScript, err := RenderProvisionScript(imageRecipe)
	if err != nil {
		return Stage{}, err
	}
	contentByPath := map[string]string{
		stage.WSLConfPath:         RenderWSLConf(imageRecipe),
		stage.ProvisionScriptPath: provisionScript,
	}
	if sudoers := RenderSudoers(imageRecipe); sudoers != "" {
		stage.SudoersPath = filepath.Join(stageDir, "sudoers")
		contentByPath[stage.SudoersPath] = sudoers
	}
	if len(options.SourceLines) > 0 {
		stage.SourcesListPath = filepath.Join(stageDir, "sources.list")
		contentByPath[stage.SourcesListPath] = strings.Join(options.SourceLines, "\n") + "\n"
	}
	if options.AutoMarks != "" {
		stage.AutoMarksPath = filepath.Join(stageDir, "auto-marks")
		contentByPath[stage.AutoMarksPath] = options.AutoMarks
	}
	for path, content := range contentByPath {
		if err := writeStageFile(path, []byte(content)); err != nil {
			return Stage{}, err
		}
	}
	if len(options.Keys) > 0 {
		stage.KeyringDir = filepath.Join(stageDir, "keys")
		if err := makeDirectoriesWithMode(stage.KeyringDir, 0o755); err != nil {
			return Stage{}, err
		}
		for name := range options.Keys {
			stage.KeyNames = append(stage.KeyNames, name)
		}
		slices.Sort(stage.KeyNames)
		for _, name := range stage.KeyNames {
			if err := writeStageFile(filepath.Join(stage.KeyringDir, KeyringFileName(name)), options.Keys[name]); err != nil {
				return Stage{}, err
			}
		}
	}
	return stage, nil
}

// writeStageFile writes a world-readable stage file whatever the umask.
func writeStageFile(path string, content []byte) error {
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return err
	}
	return os.Chmod(path, 0o644)
}

// shellQuote single-quotes value for a POSIX shell. recipe.Validate already
// constrains every recipe value; this is the second line of defense, and it
// also covers host paths such as the work directory, which frostroot does not
// choose.
func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

// CustomizeHooks returns the mmdebstrap --customize-hook arguments for stage,
// in order. Every hook fails the build on error. mmdebstrap splits the
// arguments of upload, download and copy-out with shellwords, so quoting host
// paths is correct there too. The provision script is read from the stage
// directory rather than copied into the image, so nothing is left behind.
func CustomizeHooks(stage Stage) []string {
	hooks := []string{"upload " + shellQuote(stage.WSLConfPath) + " /etc/wsl.conf"}
	if stage.SudoersPath != "" {
		hooks = append(hooks, "upload "+shellQuote(stage.SudoersPath)+" "+sudoersDropInPath)
	}
	if len(stage.KeyNames) > 0 {
		// focal's apt has no /etc/apt/keyrings; later releases ship it.
		hooks = append(hooks, `mkdir -p "$1`+ImageKeyringDir+`"`)
		for _, name := range stage.KeyNames {
			hooks = append(hooks, "upload "+shellQuote(filepath.Join(stage.KeyringDir, KeyringFileName(name)))+" "+ImageKeyringDir+"/"+KeyringFileName(name))
		}
	}
	if stage.SourcesListPath != "" {
		hooks = append(hooks, "upload "+shellQuote(stage.SourcesListPath)+" /etc/apt/sources.list")
	}
	hooks = append(hooks, `chroot "$1" /bin/sh -c "$(cat `+shellQuote(stage.ProvisionScriptPath)+`)" `+provisionScriptName)
	if stage.AutoMarksPath != "" {
		// upload makes the file root's, mode 0644, as apt's own would be.
		hooks = append(hooks, "upload "+shellQuote(stage.AutoMarksPath)+" "+aptExtendedStatesPath)
	}
	if stage.AptListsDir != "" {
		// The indexes apt verified; mmdebstrap deletes them in its cleanup,
		// after the hooks. copy-out puts "lists" inside the destination.
		hooks = append(hooks, "copy-out /var/lib/apt/lists "+shellQuote(filepath.Dir(stage.AptListsDir)))
	}
	if stage.ExtendedStatesPath != "" {
		// apt writes the file only once it has marked something, and
		// download fails on a missing file, so an image with no marks gets an
		// empty one first.
		hooks = append(hooks,
			`test -e "$1`+aptExtendedStatesPath+`" || touch "$1`+aptExtendedStatesPath+`"`,
			"download "+aptExtendedStatesPath+" "+shellQuote(stage.ExtendedStatesPath))
	}
	// Last, so that the status reflects everything installed.
	return append(hooks, "download /var/lib/dpkg/status "+shellQuote(stage.DpkgStatusPath))
}
