package builder

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/url"
	"path"
	"slices"
	"strings"
	"text/template"

	"frostroot/internal/recipe"
)

// PythonVenvPath is where every image keeps the virtual environment its
// Python packages are installed into. One fixed path per image is what lets
// the lock name it, an offline rebuild recreate it, and the compiled caches
// of two rebuilds hold the same file names.
const PythonVenvPath = "/opt/frostroot/venv"

// PythonProfilePath puts the environment on PATH for every login shell,
// which is what WSL starts.
const PythonProfilePath = "/etc/profile.d/frostroot-python.sh"

// Paths the Python step uses inside the image. The script removes all three
// before the tarball is made, so none of them reaches an image.
const (
	PythonReportPath       = "/frostroot-pip-report.json"
	PythonListPath         = "/frostroot-pip-list.json"
	PythonRequirementsPath = "/frostroot-requirements.txt"
	PythonPinPath          = "/frostroot-pip-pin.txt"
	PythonWheelsPath       = "/frostroot-wheels"
	// PythonExtraTrustPath is where certificates the build trusts but does
	// not install are uploaded, and PythonCertPath where the step
	// concatenates them with the image's own store for pip. Both are gone
	// before the tarball is made, which is what keeps --ca-bundle out of
	// the image.
	PythonExtraTrustPath = "/frostroot-extra-ca.pem"
	PythonCertPath       = "/frostroot-ca-bundle.pem"
)

// ImageTrustPath is the image's own certificate store, the file
// update-ca-certificates regenerates.
const ImageTrustPath = "/etc/ssl/certs/ca-certificates.crt"

// PinnedPip is the resolver every image's environment gets, whatever the
// release ships. Ubuntu 22.04's pip is 22.0.2 and 20.04's is 20.0.2, and
// neither can report what it installed, which is where the lock's wheels,
// checksums and URLs come from. Installing one pinned pip first means a
// recipe resolves the same way on every release, and it is pinned by
// checksum for the same reason a source's signing key is: the file decides,
// not the server. It supports Python 3.8 and up, which covers all three
// releases. The environment keeps it, so the lock records it like any other
// package and vendor fetches it like any other wheel.
var PinnedPip = recipe.LockPyPI{
	Name:     "pip",
	Version:  "24.3.1",
	Auto:     true,
	SHA256:   "3790624780082365f47549d032f3770eeb2b1e8bd1f7b2e02dace1afa361b4ed",
	Size:     1822182,
	Filename: "pip-24.3.1-py3-none-any.whl",
	URL:      "https://files.pythonhosted.org/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl",
}

// PythonWheelsDirName is what the directory of vendored wheels is called
// wherever it is staged, because copy-in gives the image a directory of the
// same name and the script installs from PythonWheelsPath.
const PythonWheelsDirName = "frostroot-wheels"

// pythonScriptName is $0 of the Python script, shown in its error messages.
const pythonScriptName = "frostroot-python"

// wheelSuffix is the only kind of file frostroot installs from. Source
// distributions are refused: building one needs a compiler in the image and
// produces files no second build can reproduce.
const wheelSuffix = ".whl"

// ErrNotAWheel is returned when a resolver reports a package that is not a
// wheel, such as a source distribution.
var ErrNotAWheel = errors.New("not a wheel")

// ErrBadPipReport is returned when pip's installation report is missing what
// the lock needs, or is a version frostroot does not know.
var ErrBadPipReport = errors.New("unusable pip report")

// pythonScriptTemplate runs as root inside the image, after the provision
// script. Recipe values are assigned once, single-quoted, and only expanded
// in double quotes afterwards, as in the provision script. Online it
// resolves the recipe's packages and writes pip's report for the lock;
// offline it installs the lock's wheels and nothing else.
var pythonScriptTemplate = template.Must(template.New("python").Funcs(template.FuncMap{"shellQuote": shellQuote}).Parse(
	`# Generated by frostroot. Runs as root inside the image during the build.
set -eu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH
{{- if .SourceDateEpoch}}
# Python writes hash-based .pyc files when this is set, instead of stamping
# each one with the moment it was compiled.
SOURCE_DATE_EPOCH={{.SourceDateEpoch}}
export SOURCE_DATE_EPOCH
{{- end}}
# Compiling a module that holds a set constant marshals it in the order that
# run's hash seed produced, and 3.8 does not sort it, so two rebuilds of one
# lock differed in a couple of hundred caches. A fixed seed makes what is
# written depend on the sources alone.
PYTHONHASHSEED=0
export PYTHONHASHSEED
# The hook inherits the build user's environment, and pip writes under $HOME:
# a real build left the builder's own /home/<name>/.cache inside the image.
# Root's home is where a root process belongs, and the cache is refused
# outright, since nothing in the image will install from it again.
HOME=/root
export HOME

# pip also reads that environment: one PIP_INDEX_URL on the build host would
# quietly resolve the recipe against another index and write its URLs into
# the lock. What a recipe resolves to must depend on the recipe alone, so
# every PIP_ variable is dropped and no configuration file is read; an index
# other than PyPI is named by the recipe, below, and by nothing else.
for pipVariable in $(env | sed -n 's/^\(PIP_[A-Za-z0-9_]*\)=.*/\1/p'); do
	unset "$pipVariable"
done
PIP_CONFIG_FILE=/dev/null
export PIP_CONFIG_FILE
{{if .CertPath}}
# pip verifies against the certificates vendored inside it rather than the
# image's, so an image that trusts the network's certificate authority is not
# enough on a network that inspects TLS: pip has to be told. --cert is how,
# and PIP_CERT left with the rest of the PIP_ environment just above.
{{- if .ExtraTrustPath}}
# This build trusts authorities the image does not install, so they are
# concatenated with the image's store into a file the step deletes. The
# image's own store comes first, so a network that inspects only some hosts
# still verifies the rest.
cat {{shellQuote .ImageTrustPath}} {{shellQuote .ExtraTrustPath}} > {{shellQuote .CertPath}}
{{- end}}
pipCert={{shellQuote .CertPath}}
{{end}}
venv={{shellQuote .VenvPath}}

python3 -m venv "$venv"
{{if .PipVersion}}
# The resolver is pinned by checksum and installed before anything else, so
# that what a recipe resolves to, and what installs it, depend on the recipe
# and not on how old this release's pip is. 20.04 ships pip 20.0.2 and 22.04
# 22.0.2, and neither can report what it installed. Offline the version comes
# from the lock, so a rebuild installs the pip its own build used.
#
# --upgrade is required: without it 20.04's pip calls the requirement
# satisfied by the pip already in the environment, downloads nothing, checks
# no hash, and goes on to install everything itself.
{{if .Offline -}}
printf 'pip==%s --hash=sha256:%s\n' {{shellQuote .PipVersion}} {{shellQuote .PipSHA256}} > {{shellQuote .PinPath}}
"$venv"/bin/python -m pip install --no-input --disable-pip-version-check --no-cache-dir --upgrade \
	--no-index --find-links {{shellQuote .WheelsPath}} \
	--require-hashes --requirement {{shellQuote .PinPath}}
{{- else if .IndexURL -}}
printf 'pip==%s --hash=sha256:%s\n' {{shellQuote .PipVersion}} {{shellQuote .PipSHA256}} > {{shellQuote .PinPath}}
"$venv"/bin/python -m pip install --no-input --disable-pip-version-check --no-cache-dir --upgrade \
	--index-url {{shellQuote .IndexURL}} \
	{{if .CertPath}}--cert "$pipCert" {{end}}--require-hashes --requirement {{shellQuote .PinPath}}
{{- else -}}
printf 'pip @ %s --hash=sha256:%s\n' {{shellQuote .PipURL}} {{shellQuote .PipSHA256}} > {{shellQuote .PinPath}}
"$venv"/bin/python -m pip install --no-input --disable-pip-version-check --no-cache-dir --upgrade \
	{{if .CertPath}}--cert "$pipCert" {{end}}--require-hashes --requirement {{shellQuote .PinPath}}
{{- end}}
rm -f {{shellQuote .PinPath}}

# That pip must be the one that does the rest. An older one cannot report what
# it installed, and it compiles the caches its own way. Offline the version
# comes from the lock, which is a text file anyone can edit, so it is assigned
# once, single-quoted, and only expanded in double quotes afterwards.
wantPip={{shellQuote .PipVersion}}
gotPip=$("$venv"/bin/python -m pip --version | cut -d' ' -f2)
if [ "$gotPip" != "$wantPip" ]; then
	echo "frostroot: pip $wantPip did not replace this release's pip; it is $gotPip" >&2
	exit 1
fi
{{end}}
{{if .Offline -}}
"$venv"/bin/python -m pip install --no-input --disable-pip-version-check --no-cache-dir \
	--no-index --find-links {{shellQuote .WheelsPath}} \
	--require-hashes --requirement {{shellQuote .RequirementsPath}}
rm -rf {{shellQuote .WheelsPath}} {{shellQuote .RequirementsPath}}

# What the environment ended up with, for frostroot to compare with the lock.
"$venv"/bin/python -m pip list --format=json --disable-pip-version-check > {{shellQuote .ListPath}}
{{- else -}}
# --upgrade so that a package the environment already seeds, such as wheel on
# 22.04, is resolved from PyPI like any other: without it pip calls the
# requirement satisfied, leaves it out of the report, and the lock would not
# record what the recipe asked for.
"$venv"/bin/python -m pip install --no-input --disable-pip-version-check --no-cache-dir \
	--only-binary=:all: --upgrade --report {{shellQuote .ReportPath}} \
	{{if .IndexURL}}--index-url {{shellQuote .IndexURL}} {{end}}{{if .CertPath}}--cert "$pipCert" {{end}}{{range .Packages}}{{shellQuote .}} {{end}}
{{- if .ExtraTrustPath}}
# Nothing this build was merely allowed to trust stays in the image.
rm -f {{shellQuote .CertPath}} {{shellQuote .ExtraTrustPath}}
{{- end}}
{{- end}}

# pip compiles as it installs, and what it writes depends on the pip and the
# Python of the release: on 20.04 a few hundred caches came out different
# between two rebuilds of one lock. Recompiling every module with hash-based
# invalidation makes the caches depend on their sources alone. A module that
# cannot be compiled is not an error here: nothing imports it during the
# build, and Python compiles what it needs at import time anyway.
"$venv"/bin/python -m compileall -q --invalidation-mode checked-hash "$venv" || true

# Every login shell finds the environment, so "python" is the image's python.
printf 'PATH="%s/bin:$PATH"\n' "$venv" > {{shellQuote .ProfilePath}}
chmod 0644 {{shellQuote .ProfilePath}}
`))

// pythonScriptValues are the values the Python script template needs.
type pythonScriptValues struct {
	VenvPath         string
	ProfilePath      string
	ReportPath       string
	ListPath         string
	RequirementsPath string
	PinPath          string
	WheelsPath       string
	PipURL           string
	PipSHA256        string
	PipVersion       string
	IndexURL         string
	Packages         []string
	Offline          bool
	SourceDateEpoch  int64
	// CertPath is what pip verifies against, "" to leave it with its own
	// certificates. ExtraTrustPath is set only when CertPath has to be
	// assembled from the image's store and uploaded certificates.
	CertPath       string
	ExtraTrustPath string
	ImageTrustPath string
}

// PythonOptions say how the Python step of a build runs.
type PythonOptions struct {
	// Offline installs the lock's wheels from PythonWheelsPath instead of
	// resolving the recipe's packages against PyPI.
	Offline bool
	// SourceDateEpoch is the instant the image is frozen at; 0 leaves it
	// out, and the compiled caches then carry the build's own time.
	SourceDateEpoch int64
	// Pip is the resolver an offline rebuild installs before anything else:
	// the pip its own online build recorded in the lock, which vendor has
	// fetched into the pool. The zero value means the lock names no pip, and
	// the environment's own does the installing. Online this field is
	// ignored and the pin is always PinnedPip.
	Pip recipe.LockPyPI
	// TrustImageCertificates makes pip verify against the image's own
	// certificate store instead of the one vendored inside it. The recipe's
	// certificate authorities are in that store by the time this step runs,
	// which is how they reach pip.
	TrustImageCertificates bool
	// ExtraTrust is certificates this build may trust that the image does
	// not install, from --ca-bundle. They are uploaded, used, and deleted.
	ExtraTrust bool
}

// RenderPythonScript renders the script that creates the image's virtual
// environment and installs the Python packages into it. It returns "" when
// the recipe asks for none, which is the signal that the build has no Python
// step at all.
func RenderPythonScript(imageRecipe recipe.Recipe, options PythonOptions) (string, error) {
	packages := imageRecipe.PythonPackages()
	if len(packages) == 0 {
		return "", nil
	}
	pin := PinnedPip
	if options.Offline {
		pin = options.Pip
	}
	// An offline step installs from a directory and reaches no network, so
	// it needs no trust at all.
	certPath, extraTrustPath := "", ""
	switch {
	case options.Offline:
	case options.ExtraTrust:
		certPath, extraTrustPath = PythonCertPath, PythonExtraTrustPath
	case options.TrustImageCertificates:
		certPath = ImageTrustPath
	}
	var script strings.Builder
	err := pythonScriptTemplate.Execute(&script, pythonScriptValues{
		VenvPath:         PythonVenvPath,
		ProfilePath:      PythonProfilePath,
		ReportPath:       PythonReportPath,
		ListPath:         PythonListPath,
		RequirementsPath: PythonRequirementsPath,
		PinPath:          PythonPinPath,
		WheelsPath:       PythonWheelsPath,
		PipURL:           pin.URL,
		PipSHA256:        pin.SHA256,
		PipVersion:       pin.Version,
		IndexURL:         imageRecipe.PythonIndexURL(),
		Packages:         packages,
		Offline:          options.Offline,
		SourceDateEpoch:  options.SourceDateEpoch,
		CertPath:         certPath,
		ExtraTrustPath:   extraTrustPath,
		ImageTrustPath:   ImageTrustPath,
	})
	if err != nil {
		return "", fmt.Errorf("rendering python script: %w", err)
	}
	return script.String(), nil
}

// RenderRequirements renders the requirements file an offline rebuild
// installs from: every wheel the lock names, pinned to its version and its
// checksum. With --require-hashes pip refuses anything else, so the file is
// the whole trust boundary of an offline Python install.
func RenderRequirements(lock recipe.Lockfile) string {
	var requirements strings.Builder
	requirements.WriteString("# Generated by frostroot from frostroot.lock.\n")
	for _, wheel := range sortedWheels(lock.PyPI) {
		fmt.Fprintf(&requirements, "%s==%s --hash=sha256:%s\n", wheel.Name, wheel.Version, wheel.SHA256)
	}
	return requirements.String()
}

// PythonResult is what the Python step of an online build produced.
type PythonResult struct {
	Wheels []recipe.LockPyPI // every installed package, sorted by name
	// PipVersion and Interpreter are the tools that resolved the wheels.
	// Another pip, or another Python, may resolve another set, the way
	// another mmdebstrap may lay out another image.
	PipVersion  string
	Interpreter string // python_full_version, such as 3.12.3
}

// pipReport is pip's installation report, the JSON --report writes. Only the
// fields the lock needs are decoded.
type pipReport struct {
	Version     string          `json:"version"`
	PipVersion  string          `json:"pip_version"`
	Environment map[string]any  `json:"environment"`
	Install     []pipReportItem `json:"install"`
}

type pipReportItem struct {
	Requested bool `json:"requested"`
	Metadata  struct {
		Name    string `json:"name"`
		Version string `json:"version"`
	} `json:"metadata"`
	DownloadInfo struct {
		URL         string `json:"url"`
		ArchiveInfo struct {
			Hash   string            `json:"hash"`
			Hashes map[string]string `json:"hashes"`
		} `json:"archive_info"`
	} `json:"download_info"`
}

// pipReportVersion is the report format frostroot reads. pip promises to
// bump the major part when the shape changes, so a different one is refused
// rather than guessed at.
const pipReportVersion = "1"

// ParsePipReport reads pip's installation report and returns what the lock
// records. requested are the recipe's Python package names: every one of
// them must appear in the report, or the build did not install what the
// recipe asked for.
func ParsePipReport(reportReader io.Reader, requested []string) (PythonResult, error) {
	var report pipReport
	if err := json.NewDecoder(reportReader).Decode(&report); err != nil {
		return PythonResult{}, fmt.Errorf("%w: %w", ErrBadPipReport, err)
	}
	if major, _, _ := strings.Cut(report.Version, "."); major != pipReportVersion {
		return PythonResult{}, fmt.Errorf("%w: version %q, want %s", ErrBadPipReport, report.Version, pipReportVersion)
	}
	if len(report.Install) == 0 {
		return PythonResult{}, fmt.Errorf("%w: it installed nothing", ErrBadPipReport)
	}
	result := PythonResult{PipVersion: report.PipVersion}
	if version, ok := report.Environment["python_full_version"].(string); ok {
		result.Interpreter = version
	}
	for _, item := range report.Install {
		wheel, err := wheelFromReport(item)
		if err != nil {
			return PythonResult{}, err
		}
		result.Wheels = append(result.Wheels, wheel)
	}
	// The script installed the pinned resolver into the same environment, so
	// the lock records it too: it is part of what the image holds, and an
	// offline rebuild installs it from the pool like everything else.
	result.Wheels = sortedWheels(withPinnedPip(result.Wheels))
	if err := checkRequestedArePresent(requested, result.Wheels); err != nil {
		return PythonResult{}, err
	}
	return result, nil
}

// withPinnedPip adds the pinned pip, unless the resolution already decided a
// pip of its own, in which case the report is the truth about the image and
// LockedPip hands that one to the offline rebuild.
func withPinnedPip(wheels []recipe.LockPyPI) []recipe.LockPyPI {
	for _, wheel := range wheels {
		if recipe.NormalizePythonName(wheel.Name) == "pip" {
			return wheels
		}
	}
	return append(wheels, PinnedPip)
}

// LockedPip returns the pip a lock records, which an offline rebuild installs
// into the environment before anything else. The zero value means the lock
// names none, and the environment's own pip does the installing.
func LockedPip(lock recipe.Lockfile) recipe.LockPyPI {
	for _, wheel := range lock.PyPI {
		if recipe.NormalizePythonName(wheel.Name) == "pip" {
			return wheel
		}
	}
	return recipe.LockPyPI{}
}

// wheelFromReport turns one entry of pip's report into a lock entry, or says
// what the entry lacks.
func wheelFromReport(item pipReportItem) (recipe.LockPyPI, error) {
	name, version := item.Metadata.Name, item.Metadata.Version
	if name == "" || version == "" {
		return recipe.LockPyPI{}, fmt.Errorf("%w: an entry has no name or version", ErrBadPipReport)
	}
	digest := item.DownloadInfo.ArchiveInfo.Hashes["sha256"]
	if digest == "" {
		// pip's older single hash, "sha256=<hex>".
		if algorithm, hexDigest, found := strings.Cut(item.DownloadInfo.ArchiveInfo.Hash, "="); found && algorithm == "sha256" {
			digest = hexDigest
		}
	}
	if digest == "" {
		return recipe.LockPyPI{}, fmt.Errorf("%w: %s %s has no sha256", ErrBadPipReport, name, version)
	}
	fileName, err := wheelFileName(item.DownloadInfo.URL)
	if err != nil {
		return recipe.LockPyPI{}, fmt.Errorf("%s %s: %w", name, version, err)
	}
	return recipe.LockPyPI{
		Name:     name,
		Version:  version,
		Auto:     !item.Requested,
		SHA256:   digest,
		Filename: fileName,
		URL:      item.DownloadInfo.URL,
	}, nil
}

// wheelFileName returns the file name a wheel URL ends in, or says why the
// URL cannot be vendored: it must be an https URL naming a .whl file, since
// vendor/wheels is filled from it and pip installs from that directory.
func wheelFileName(wheelURL string) (string, error) {
	parsed, err := url.Parse(wheelURL)
	if err != nil || parsed.Scheme != "https" || parsed.Host == "" {
		return "", fmt.Errorf("%w: %q is not an https url", ErrBadPipReport, wheelURL)
	}
	fileName := path.Base(parsed.Path)
	if !strings.HasSuffix(fileName, wheelSuffix) {
		return "", fmt.Errorf("%w: %s (only wheels can be locked; ask for the apt package instead)", ErrNotAWheel, fileName)
	}
	if fileName != path.Clean(fileName) || strings.ContainsAny(fileName, `/\`) || strings.HasPrefix(fileName, ".") {
		return "", fmt.Errorf("%w: %q is not a file name", ErrBadPipReport, fileName)
	}
	return fileName, nil
}

// checkRequestedArePresent reports a recipe package the report does not
// mention, which would mean the image lacks something the recipe asked for.
func checkRequestedArePresent(requested []string, wheels []recipe.LockPyPI) error {
	installed := make(map[string]bool, len(wheels))
	for _, wheel := range wheels {
		installed[recipe.NormalizePythonName(wheel.Name)] = true
	}
	var missing []string
	for _, name := range requested {
		if !installed[recipe.NormalizePythonName(name)] {
			missing = append(missing, name)
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("%w: it does not mention %s", ErrBadPipReport, strings.Join(missing, ", "))
	}
	return nil
}

// PythonInstalled is one package of an image's environment, as pip lists it.
type PythonInstalled struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// pythonSeedPackages are what python3 -m venv puts in an environment before
// frostroot installs anything: pip always, and setuptools beside it on 22.04
// and 20.04. Finding one the lock does not name is not a difference, because
// nothing asked for it — a lock with no pip of its own is rebuilt by the
// environment's, which is then exactly such a package. A lock that does name
// one is another matter: pip installed that version, and it is compared like
// any other.
var pythonSeedPackages = []string{"pip", "setuptools", "wheel", "pkg-resources"}

// ParsePipList reads the package list an offline build downloads out of the
// image, written by "pip list --format=json".
func ParsePipList(listReader io.Reader) ([]PythonInstalled, error) {
	var installed []PythonInstalled
	if err := json.NewDecoder(listReader).Decode(&installed); err != nil {
		return nil, fmt.Errorf("reading the image's package list: %w", err)
	}
	return installed, nil
}

// ComparePythonWithLock reports how the image's virtual environment differs
// from the lock: a package missing, one at another version, or one the lock
// does not name. It is the Python half of the check an offline build makes
// before anything is placed, and it is what makes --require-hashes a result
// rather than a promise.
func ComparePythonWithLock(lock recipe.Lockfile, installed []PythonInstalled) error {
	lockedVersions := make(map[string]string, len(lock.PyPI))
	for _, wheel := range lock.PyPI {
		lockedVersions[recipe.NormalizePythonName(wheel.Name)] = wheel.Version
	}
	var differences []string
	found := map[string]bool{}
	for _, installedPackage := range installed {
		name := recipe.NormalizePythonName(installedPackage.Name)
		lockedVersion, inLock := lockedVersions[name]
		if !inLock && slices.Contains(pythonSeedPackages, name) {
			continue
		}
		found[name] = true
		switch {
		case !inLock:
			differences = append(differences, fmt.Sprintf("%s %s is in the environment but not in the lock", name, installedPackage.Version))
		case lockedVersion != installedPackage.Version:
			differences = append(differences, fmt.Sprintf("%s is %s in the environment and %s in the lock", name, installedPackage.Version, lockedVersion))
		}
	}
	for name, version := range lockedVersions {
		if !found[name] {
			differences = append(differences, fmt.Sprintf("%s %s is in the lock but not in the environment", name, version))
		}
	}
	if len(differences) == 0 {
		return nil
	}
	slices.Sort(differences)
	return fmt.Errorf("%w: %s", ErrImageDiffersFromLock, strings.Join(differences, "; "))
}

// sortedWheels returns wheels ordered by the name PyPI compares, so that the
// lock's order depends on the package set and nothing else.
func sortedWheels(wheels []recipe.LockPyPI) []recipe.LockPyPI {
	sorted := slices.Clone(wheels)
	slices.SortFunc(sorted, func(left, right recipe.LockPyPI) int {
		return strings.Compare(recipe.NormalizePythonName(left.Name), recipe.NormalizePythonName(right.Name))
	})
	return sorted
}
